# fly.toml app configuration file generated for jahns on 2024-01-27T22:25:45-03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jahns'
primary_region = 'yul'
kill_signal = 'SIGTERM'

[build]

[env]
DATABASE_PATH = '/mnt/jahns_data/jahns.db'
PHX_HOST = 'jahns.fly.dev'
PORT = '8080'

[mounts]
source = 'jahns_data'
destination = '/mnt/jahns_data/'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[vm]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
